stages:
  - Static Analysis
  - Test

variables:
    GIT_STRATEGY: clone
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
before_script:
    - mkdir -p .cache/pip
    - export PATH=$PATH:/usr/local/bin
cache:
    paths:
      - .cache/pip



flake8:
  stage: Static Analysis

  image: centos
  script:
    - yum install python3.8 -y
    - yum install python3-pip -y
    - python3 --version
    - pip3 install -r requirements.txt
    - flake8

pytest:
  stage: Test
  image: centos
  script:
    - yum install python3.8 -y
    - yum install python3-pip -y
    - python3 --version
    - pip3 install -r requirements.txt
    - pytest
