stages:
  - Static Analysis
  - Test


flake8:
  stage: Static Analysis
  image: centos
  script:
    - yum install python3.8 -y
    - yum install python3-pip -y
    - python3 --version
    - pip3 install -r requirements.txt
    - flake8

pytest:
  stage: Test
  image: centos
  script:
    - yum install python3.8 -y
    - yum install python3-pip -y
    - python3 --version
    - pip3 install -r requirements.txt
    - pytest
