stages:
  - Static Analysis
  - Test
before_script:
  - export PATH=$PATH:/usr/local/bin


flake8:
  stage: Static Analysis
  image: centos7
  script:
    - yum install python3.8 -y
    - yum install python3-pip -y
    - python3 --version
    - pip3 install -r requirements.txt
    - flake8

pytest:
  stage: Test
  image: centos7
  script:
    - yum install python3.8 -y
    - yum install python3-pip -y
    - python3 --version
    - pip3 install -r requirements.txt
    - pytest
