# Generated by Django 3.1.1 on 2020-10-10 10:59

from django.db import migrations, models
import django.db.models.deletion
import tsvector_field


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0010_delete_film'),
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created date')),
                ('updated_date', models.DateTimeField(auto_now=True, null=True, verbose_name='created date')),
                ('title', models.CharField(db_index=True, max_length=30)),
                ('description', models.TextField()),
                ('release_year', models.SmallIntegerField()),
                ('rental_duration', models.SmallIntegerField(default=3)),
                ('rental_rate', models.DecimalField(decimal_places=2, default=4.99, max_digits=4)),
                ('length', models.SmallIntegerField()),
                ('replacement_cost', models.DecimalField(decimal_places=2, default=19.99, max_digits=5)),
                ('rating', models.CharField(choices=[('R', 'R'), ('PG-13', 'PG-13'), ('NC-17', 'NC-17')], max_length=5)),
                ('last_update', models.DateTimeField()),
                ('special_features', models.TextField()),
                ('fulltext', tsvector_field.SearchVectorField()),
                ('cover', models.ImageField(null=True, upload_to='media/cover')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.language')),
            ],
            options={
                'db_table': 'movie_film',
                'ordering': ['last_update'],
            },
        ),
    ]
