# Generated by Django 3.1.1 on 2020-10-11 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_actor'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilmActor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateTimeField()),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.actor')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.film')),
            ],
            options={
                'db_table': 'movie_film_actor',
                'ordering': ['last_update'],
            },
        ),
        migrations.AddField(
            model_name='actor',
            name='film',
            field=models.ManyToManyField(through='movie.FilmActor', to='movie.Film'),
        ),
    ]
