# Generated by Django 3.1.1 on 2020-10-12 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_city'),
        ('movie', '0003_auto_20201011_2018'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilmCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateTimeField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.category')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.film')),
            ],
            options={
                'db_table': 'movie_film_category',
                'ordering': ['last_update'],
            },
        ),
        migrations.AddField(
            model_name='film',
            name='category',
            field=models.ManyToManyField(through='movie.FilmCategory', to='base.Category'),
        ),
    ]
