# Generated by Django 3.1.1 on 2020-11-03 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_auto_20201030_1708'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actor',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='actor',
            name='last_name',
        ),
    ]
