# Generated by Django 3.1.1 on 2020-11-03 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_auto_20201103_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='last_update',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
