# Generated by Django 3.1.1 on 2020-11-03 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0009_auto_20201103_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='release_year',
            field=models.SmallIntegerField(),
        ),
    ]
