# Generated by Django 3.1.1 on 2020-11-04 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0010_auto_20201103_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='title',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
