# Generated by Django 3.1.1 on 2020-11-06 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0011_auto_20201104_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
