# Generated by Django 3.1.1 on 2021-01-12 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0015_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='cover',
            field=models.ImageField(null=True, upload_to='cover'),
        ),
    ]
