# Generated by Django 3.1.1 on 2020-10-05 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20201005_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='last_update',
            field=models.DateTimeField(),
        ),
    ]
