# Generated by Django 3.1.1 on 2020-10-05 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20201005_1424'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['last_update']},
        ),
    ]
