# Generated by Django 3.1.1 on 2020-10-10 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_film'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Film',
        ),
    ]
