# Generated by Django 3.1.1 on 2020-10-25 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='fa_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='fa_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='fa_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='language',
            name='fa_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
