# Generated by Django 3.1.1 on 2020-10-12 16:21

from django.db import migrations, models
import user.validator


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created date')),
                ('updated_date', models.DateTimeField(auto_now=True, null=True, verbose_name='created date')),
                ('phone_number', models.CharField(max_length=50, validators=[user.validator.phone_validator])),
                ('is_active', models.BooleanField()),
                ('phone_type', models.CharField(choices=[('phone', 'mobile')], max_length=150)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
