# Generated by Django 3.1.1 on 2020-10-13 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20201012_2244'),
        ('user', '0004_auto_20201013_1900'),
    ]

    operations = [
    ]
