# Generated by Django 3.1.1 on 2020-10-13 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_template'),
        ('user', '0005_merge_20201013_2209'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created date')),
                ('updated_date', models.DateTimeField(auto_now=True, null=True, verbose_name='created date')),
                ('message', models.CharField(choices=[('DRAFT', 'draft'), ('SEND', 'send')], max_length=150)),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.phone')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.template')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='phone',
            name='template',
            field=models.ManyToManyField(through='user.Sms', to='base.Template'),
        ),
    ]
