# Generated by Django 3.1.1 on 2021-02-03 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_verification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='verification',
            old_name='verfication',
            new_name='verification',
        ),
    ]
